build_mau:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: FINANCE_DB
      warehouse: COMPUTE_WH
      schema: ANALYTICS
      threads: 1
      type: snowflake
  target: dev
